# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'assignment_02'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'assignment_02'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Remove +schema configurations to use default schema
models:
  assignment_02:
    staging:
      +materialized: view
      # Removed +schema: dbt_nyadav
    
    intermediate:
      +materialized: view
      # Removed +schema: dbt_nyadav
    
    marts:
      +materialized: table
      # Removed +schema: dbt_nyadav

# Seeds configuration
seeds:
  assignment_02:
    +materialized: table
    # Removed +schema: dbt_nyadav

# Snapshots configuration
snapshots:
  assignment_02:
    # Removed +target_schema: dbt_nyadav